name: Cypress Tests

on:
  pull_request:
    branches:
      - '**' # Matches all branches

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Upload Cypress screenshots and videos (if any)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
